### ISSUE TITLE
username: matched[1], TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by elderalves** [xiaoyann/deploy-kit#2]
I tried to use this plugin for webpack only for tests in the first time, however I got this error:

`username: matched[1],
                     ^
TypeError: Cannot read property '1' of null`

This is my `deploy.js`:

```
const client = require("deploy-kit");

client.sftp({
  
  server: 'myuser:password@111.111.111.111:222',
  workspace: __dirname,
  ignore: '**/*.map',
  deployTo: './public_html/somefolder',
  rules: [
    {
      test: /dist\/(.*)$/,
      dest: 'public/static/[$1]'
    },
    {
      test: /views\/((?:[^/]+\/)*?[^\/]+).html$/,
      dest: 'app/views/[$1].phtml'
    }
  ]
})
.exec()
```

To post here I change my user info for dummy text, but it was placed right.

**Comment by xiaoyann** [comment]
The "server" option you given can't match correctly. Please refer to here 
https://github.com/xiaoyann/deploy-kit/blob/master/lib/deploy.js#L42-L47
